// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// llRecruit
double llRecruit(NumericVector params);
RcppExport SEXP crrecruit_llRecruit(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    __result = Rcpp::wrap(llRecruit(params));
    return __result;
END_RCPP
}
// PrNotDetect
double PrNotDetect(NumericVector params);
RcppExport SEXP crrecruit_PrNotDetect(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    __result = Rcpp::wrap(PrNotDetect(params));
    return __result;
END_RCPP
}
// ExpectedCapture
NumericVector ExpectedCapture(NumericVector params);
RcppExport SEXP crrecruit_ExpectedCapture(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    __result = Rcpp::wrap(ExpectedCapture(params));
    return __result;
END_RCPP
}
// ExpectedFirstCapture
NumericVector ExpectedFirstCapture(NumericVector params);
RcppExport SEXP crrecruit_ExpectedFirstCapture(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    __result = Rcpp::wrap(ExpectedFirstCapture(params));
    return __result;
END_RCPP
}
