# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llRecruit <- function(params) {
    .Call('crrecruit_llRecruit', PACKAGE = 'crrecruit', params)
}

PrNotDetect <- function(params) {
    .Call('crrecruit_PrNotDetect', PACKAGE = 'crrecruit', params)
}

ExpectedCapture <- function(params) {
    .Call('crrecruit_ExpectedCapture', PACKAGE = 'crrecruit', params)
}

ExpectedFirstCapture <- function(params) {
    .Call('crrecruit_ExpectedFirstCapture', PACKAGE = 'crrecruit', params)
}

